### ISSUE TITLE
container won't start

### ISSUE THREAD

**Issue by dkutac** [lscalese/objectscript-syntax-for-gitlab#1]
06/03/22-07:38:05:695 (447) 0 [Database.MountedRO] Mounted database /usr/irissys/mgr/enslib/ (SFN 6) read-only. Database label is marked read-only.
06/03/22-07:38:05:696 (447) 0 [Utility.Event] Initializing Interoperability during system startup
[INFO] ...started InterSystems IRIS instance IRIS
[INFO] Executing command sh /home/irisowner/startRackup.sh...
[ERROR] /home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:489:in `<module:Lexers>': uninitialized constant Rouge::Lexers::SQL (NameError)
        from /home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:5:in `<module:Rouge>'
        from /home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:4:in `<top (required)>'
        from /home/irisowner/rouge/lib/rouge/lexer.rb:532:in `load'
        from /home/irisowner/rouge/lib/rouge/lexer.rb:532:in `load_lexer'
        from /home/irisowner/rouge/lib/rouge.rb:54:in `block in load_lexers'
        from /home/irisowner/rouge/lib/rouge.rb:53:in `each'
        from /home/irisowner/rouge/lib/rouge.rb:53:in `load_lexers'
        from /home/irisowner/rouge/lib/rouge.rb:69:in `<top (required)>'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:60:in `require'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:55:in `each'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:55:in `block in require'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:44:in `each'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:44:in `require'
        from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler.rb:176:in `require'
        from /home/irisowner/rouge/spec/visual/app.rb:6:in `<top (required)>'
        from /home/irisowner/rouge/config.ru:6:in `load'
        from /home/irisowner/rouge/config.ru:6:in `block in <main>'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:168:in `start'
        from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/bin/rackup:5:in `<top (required)>'
root@u4docker:/home/kutac/objectscript-syntax-for-gitlab#
        from /home/irisowner/rouge/vendor/ruby/2.7.0/bin/rackup:23:in `<main>'
06/03/22-07:38:05:785 (468) 0 [Utility.Event] Private webserver started on 52773

**Comment by lscalese** [comment]
Hi @dkutac ,

I check now.
Thank you!

**Comment by lscalese** [comment]
Re @dkutac,

I tested, but I could not reproduce the problem.  

Could you please check, if you have the latest version of this repository?
Recently I change the procedure.  
Users don't need to build the container.  Have you retrieved the image with : 

```bash
docker pull ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest
```

docker-compose file has been also updated : 

```
version: '3.6'
services:
  iris:
    image: ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    #restart: always
    command: ["--check-caps", "false", "-a", "sh /home/irisowner/startRackup.sh"]
    ports: 
      - 1972
      - 9692:52773
      - 53773
      - "9592:9292"
    volumes:
      - ./:/irisrun/repo
```

What is your operating system?

Thank you.

**Comment by dkutac** [comment]
root@u4docker:/home/kutac/objectscript-syntax-for-gitlab# docker pull ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest
latest: Pulling from lscalese/objectscript-syntax-for-gitlab
Digest: sha256:ee9630dd590b2104aaa5760c0b2a34b6011ebc3f11bbf80c8782cb1bac167ea6
Status: Image is up to date for ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest
ghcr.io/lscalese/objectscript-syntax-for-gitlab:latest


root@u4docker:/home/kutac/objectscript-syntax-for-gitlab# docker version
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086349
 Built:             Thu Mar 24 17:14:32 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 17:15:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

I run virtualized ubuntu 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal


HTH

Dan

**Comment by lscalese** [comment]
Thank you for these information Dan @dkutac!

I have the same docker version and I run to PopOS (Ubuntu base).  
The problem seems located in Ruby code execution, but I don't understand why I don't have the same behaviour yet.

Maybe could you try without starting the ruby project.  In docker-compose, change the "command" like this : 

```
command: ["--check-caps", "false"]
```

Then start the container with the command `docker-compose up`
Open a bash terminal in the container `docker exec -it objectscript-syntax-for-gitlab_iris_1 bash`, then :

```bash
ruby -v
cd /home/irisowner/rouge/
bundle config set path 'vendor'
bundle install
bundle exec rackup --host 0.0.0.0
```

I'm curious about the output.
If you have the time, could you try this and send me output please ?

Thank you.
Lorenzo.

**Comment by dkutac** [comment]
root@u4docker:/home/kutac# docker exec -it objectscript-syntax-for-gitlab_iris_1 bash
irisowner@d08b5b143d92:~/irisbuild$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
irisowner@d08b5b143d92:~/irisbuild$ bundle config set path 'vendor'
irisowner@d08b5b143d92:~/irisbuild$ bundle install
**Could not locate Gemfile**

**Comment by dkutac** [comment]
Bundle complete! 15 Gemfile dependencies, 34 gems now installed.
Bundled gems are installed into `./vendor`
irisowner@d08b5b143d92:~/rouge$ bundle exec rackup --host 0.0.0.0
Traceback (most recent call last):
        32: from /home/irisowner/rouge/vendor/ruby/2.7.0/bin/rackup:23:in `<main>'
        31: from /home/irisowner/rouge/vendor/ruby/2.7.0/bin/rackup:23:in `load'
        30: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/bin/rackup:5:in `<top (required)>'
        29: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:168:in `start'
        28: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        27: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        26: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        25: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        24: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        23: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        22: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        21: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        20: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        19: from /home/irisowner/rouge/vendor/ruby/2.7.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        18: from /home/irisowner/rouge/config.ru:6:in `block in <main>'
        17: from /home/irisowner/rouge/config.ru:6:in `load'
        16: from /home/irisowner/rouge/spec/visual/app.rb:6:in `<top (required)>'
        15: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler.rb:176:in `require'
        14: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:44:in `require'
        13: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:44:in `each'
        12: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:55:in `block in require'
        11: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:55:in `each'
        10: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
         9: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/runtime.rb:60:in `require'
         8: from /home/irisowner/rouge/lib/rouge.rb:69:in `<top (required)>'
         7: from /home/irisowner/rouge/lib/rouge.rb:53:in `load_lexers'
         6: from /home/irisowner/rouge/lib/rouge.rb:53:in `each'
         5: from /home/irisowner/rouge/lib/rouge.rb:54:in `block in load_lexers'
         4: from /home/irisowner/rouge/lib/rouge/lexer.rb:532:in `load_lexer'
         3: from /home/irisowner/rouge/lib/rouge/lexer.rb:532:in `load'
         2: from /home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:4:in `<top (required)>'
         1: from /home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:5:in `<module:Rouge>'
/home/irisowner/rouge/lib/rouge/lexers/objectscript.rb:489:in `<module:Lexers>': uninitialized constant Rouge::Lexers::SQL (NameError)
irisowner@d08b5b143d92:~/rouge$

**Comment by lscalese** [comment]
Hi @dkutac!

Thank you for your tests.
I just make a fresh virtualized install of Ubuntu 20.04 lts (using Virtual Box).  
Only docker and docker-compose software has been added.  
Unfortunately, the procedure works.  

I have trouble reproducing this error and work to effectively resolve this bug.  
It's a bit strange to have different behaviour with the same image.  
Unfortunately this afternoon I'm not available.  I'll try again to reproduce this error tomorrow.  

Lorenzo.

**Comment by dkutac** [comment]
sorry to trouble you @lscalese , it might be just my VM and docker or something else....

Dan
